### ISSUE TITLE
How can I calculate Average Angle in the experiment？

### ISSUE THREAD

**Issue by Lzh-5299** [testingautomated-usi/DeepHyperion#8]
I can‘t the method of calculating Average Angle in the code.And if the feature “bitmap” is Luminosity descrited in your paper?

**Comment by zohdit** [comment]
> I can‘t the method of calculating Average Angle in the code.And if the feature “bitmap” is Luminosity descrited in your paper?

As mentioned in the paper AverageAngle metric did not correlate with the smoothness feature we defined in the pilot study for feature selection. Therefore, we discard it from the tool release.

and,  the "bitmap_count" method in DeepHyperion-MNIST/features.py is to compute Luminosity.

**Comment by zohdit** [comment]
Average Angle computation is added here: [AvgAngle](https://github.com/testingautomated-usi/DeepHyperion/commit/6fab8f31ef80b1bee20116b1e3bce0ace68d6c06)

**Comment by Lzh-5299** [comment]
Thank you for your answer! I have another question.How to create the feature map(Fig 1) in your paper?Does the code here contain how to generate it?

**Comment by zohdit** [comment]
Fig 1, is manually generated to motivate the idea.
